from app.models import (
    Persona, Client, Driver, Geoposition, Review,
    Car, CarType, OrderStatus, Order, Payment
)


TABLE_MODELS = {}
models_config = [
    (['клиент', 'клиенты', 'client', 'clients'], Client),
    (['водитель', 'водители', 'driver', 'drivers'], Driver),
    (['геопозиция', 'геопозиции', 'geoposition', 'geopositions'], Geoposition),
    (['отзыв', 'отзывы', 'review', 'reviews'], Review),
    (['автомобиль', 'машина', 'автомобили', 'машины', 'car', 'cars'], Car),
    (['тип_авто', 'типы_авто', 'cartype', 'cartypes', 'car_type', 'car_types'], CarType),
    (['статус_заказа', 'статусзаказа', 'статусы_заказов', 'статусызаказов',
      'orderstatus', 'orderstatuses', 'order_status', 'order_statuses'], OrderStatus),
    (['заказ', 'заказы', 'order', 'orders'], Order),
    (['оплата', 'оплаты', 'чек', 'чеки', 'payment', 'payments'], Payment)
]

for aliases, model in models_config:
    for alias in aliases:
        TABLE_MODELS[alias] = model


COLUMN_MAPPINGS = {
    Persona: {
        'имя': 'name',
        'name': 'name',
        'телефон': 'phone',
        'phone': 'phone',
        'дата_регистрации': 'registration_date',
        'registration_date': 'registration_date',
        'день_рождения': 'birthday',
        'birthday': 'birthday',
    },
    Client: {
        'имя': 'name',
        'name': 'name',
        'телефон': 'phone',
        'phone': 'phone',
        'дата_регистрации': 'registration_date',
        'registration_date': 'registration_date',
        'день_рождения': 'birthday',
        'birthday': 'birthday',
        # Клиент
        'id_клиента': 'id',
        'id': 'id',
        'фамилия': 'surname',
        'surname': 'surname',
        'email': 'email',
    },
    Driver: {
        'имя': 'name',
        'name': 'name',
        'телефон': 'phone',
        'phone': 'phone',
        'дата_регистрации': 'registration_date',
        'registration_date': 'registration_date',
        'день_рождения': 'birthday',
        'birthday': 'birthday',
        # Водитель
        'id_водителя': 'id',
        'id': 'id',
        'фамилия': 'surname',
        'surname': 'surname',
        'номер_лицензии': 'license_number',
        'license_number': 'license_number',
        'работает': 'is_working',
        'is_working': 'is_working',
        'id_авто': 'car_id',
        'car_id': 'car_id',
    },
    Geoposition: {
        'id_персоны': 'persona_id',
        'persona_id': 'persona_id',
        'широта': 'latitude',
        'latitude': 'latitude',
        'долгота': 'longitude',
        'longitude': 'longitude',
        'время_отметки': 'mark_time',
        'mark_time': 'mark_time',
    },
    Review: {
        'id_написавшего': 'author_id',
        'author_id': 'author_id',
        'id_цели': 'target_id',
        'target_id': 'target_id',
        'оценка': 'rating',
        'rating': 'rating',
        'комментарий': 'comment',
        'comment': 'comment',
        'дата_создания': 'creation_date',
        'creation_date': 'creation_date',
    },
    Car: {
        'марка': 'brand',
        'brand': 'brand',
        'модель': 'model',
        'model': 'model',
        'гос_номер': 'license_plate',
        'license_plate': 'license_plate',
        'цвет': 'color',
        'color': 'color',
        'год': 'year',
        'год_выпуска': 'year',
        'year': 'year',
        'личный': 'is_personal',
        'is_personal': 'is_personal',
        'тип_авто': 'car_type_id',
        'car_type_id': 'car_type_id',
    },
    CarType: {
        'название': 'name',
        'name': 'name',
    },
    OrderStatus: {
        'значение_статуса': 'value',
        'value': 'value',
    },
    Order: {
        'время_заказа': 'order_time',
        'order_time': 'order_time',
        'время_прибытия': 'arrival_time',
        'arrival_time': 'arrival_time',
        'адрес_отправления': 'departure_address',
        'departure_address': 'departure_address',
        'адрес_назанчения': 'destination_address',
        'destination_address': 'destination_address',
        'расстояние_м': 'distance_m',
        'distance_m': 'distance_m',
        'статус_заказа': 'status_id',
        'status_id': 'status_id',
        'id_водителя': 'driver_id',
        'driver_id': 'driver_id',
        'id_клиента': 'client_id',
        'client_id': 'client_id',
        'колво_пассажиров': 'passenger_count',
        'passenger_count': 'passenger_count',
        'животные': 'has_animals',
        'has_animals': 'has_animals',
        'дети': 'has_children',
        'has_children': 'has_children',
        'багаж': 'has_luggage',
        'has_luggage': 'has_luggage',
    },
    Payment: {
        'id_заказа': 'order_id',
        'order_id': 'order_id',
        'id_клиента': 'client_id',
        'client_id': 'client_id',
        'сумма': 'amount',
        'amount': 'amount',
        'дата_оплаты': 'payment_date',
        'payment_date': 'payment_date',
        'тип_оплаты': 'payment_type',
        'payment_type': 'payment_type',
    },
}
LINE = f"{'=' * 60}"
